/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "SimpleTokenMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleTokenMinter__factory>;
    getContractFactory(
      name: "TestHTS",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestHTS__factory>;
    getContractFactory(
      name: "TestHTSWithCombinedKeys",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestHTSWithCombinedKeys__factory>;
    getContractFactory(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService__factory>;
    getContractFactory(
      name: "IndexTokenController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexTokenController__factory>;
    getContractFactory(
      name: "IndexVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexVault__factory>;
    getContractFactory(
      name: "IGovernanceHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGovernanceHook__factory>;
    getContractFactory(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService__factory>;
    getContractFactory(
      name: "IIndexVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIndexVault__factory>;
    getContractFactory(
      name: "MockHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHederaTokenService__factory>;

    getContractAt(
      name: "SimpleTokenMinter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleTokenMinter>;
    getContractAt(
      name: "TestHTS",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestHTS>;
    getContractAt(
      name: "TestHTSWithCombinedKeys",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestHTSWithCombinedKeys>;
    getContractAt(
      name: "IHederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHederaTokenService>;
    getContractAt(
      name: "IndexTokenController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexTokenController>;
    getContractAt(
      name: "IndexVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexVault>;
    getContractAt(
      name: "IGovernanceHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGovernanceHook>;
    getContractAt(
      name: "IHederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHederaTokenService>;
    getContractAt(
      name: "IIndexVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIndexVault>;
    getContractAt(
      name: "MockHederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHederaTokenService>;

    deployContract(
      name: "SimpleTokenMinter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleTokenMinter>;
    deployContract(
      name: "TestHTS",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestHTS>;
    deployContract(
      name: "TestHTSWithCombinedKeys",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestHTSWithCombinedKeys>;
    deployContract(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "IndexTokenController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexTokenController>;
    deployContract(
      name: "IndexVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexVault>;
    deployContract(
      name: "IGovernanceHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGovernanceHook>;
    deployContract(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "IIndexVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIndexVault>;
    deployContract(
      name: "MockHederaTokenService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHederaTokenService>;

    deployContract(
      name: "SimpleTokenMinter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleTokenMinter>;
    deployContract(
      name: "TestHTS",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestHTS>;
    deployContract(
      name: "TestHTSWithCombinedKeys",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestHTSWithCombinedKeys>;
    deployContract(
      name: "IHederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "IndexTokenController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexTokenController>;
    deployContract(
      name: "IndexVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexVault>;
    deployContract(
      name: "IGovernanceHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGovernanceHook>;
    deployContract(
      name: "IHederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "IIndexVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIndexVault>;
    deployContract(
      name: "MockHederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHederaTokenService>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
