/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DepositMinter } from "./DepositMinter";
export type { IHederaTokenService } from "./IHederaTokenService";
