/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleTokenMinter__factory } from "./SimpleTokenMinter__factory";
export { TestHTS__factory } from "./TestHTS__factory";
export { TestHTSWithCombinedKeys__factory } from "./TestHTSWithCombinedKeys__factory";
