/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IHederaTokenService {
  export type HederaTokenStruct = {
    name: string;
    symbol: string;
    treasury: AddressLike;
    memo: string;
    supplyType: boolean;
    maxSupply: BigNumberish;
    freezeDefault: boolean;
    freezeKey: AddressLike[];
    wipeKey: AddressLike[];
    supplyKey: AddressLike[];
    adminKey: AddressLike[];
    kycKey: AddressLike[];
    decimals: BigNumberish;
    autoRenewAccount: AddressLike;
    autoRenewPeriod: BigNumberish;
  };

  export type HederaTokenStructOutput = [
    name: string,
    symbol: string,
    treasury: string,
    memo: string,
    supplyType: boolean,
    maxSupply: bigint,
    freezeDefault: boolean,
    freezeKey: string[],
    wipeKey: string[],
    supplyKey: string[],
    adminKey: string[],
    kycKey: string[],
    decimals: bigint,
    autoRenewAccount: string,
    autoRenewPeriod: bigint
  ] & {
    name: string;
    symbol: string;
    treasury: string;
    memo: string;
    supplyType: boolean;
    maxSupply: bigint;
    freezeDefault: boolean;
    freezeKey: string[];
    wipeKey: string[];
    supplyKey: string[];
    adminKey: string[];
    kycKey: string[];
    decimals: bigint;
    autoRenewAccount: string;
    autoRenewPeriod: bigint;
  };
}

export declare namespace MockHederaTokenService {
  export type TransferStruct = {
    from: AddressLike;
    to: AddressLike;
    amount: BigNumberish;
  };

  export type TransferStructOutput = [
    from: string,
    to: string,
    amount: bigint
  ] & { from: string; to: string; amount: bigint };
}

export interface MockHederaTokenServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "allowance(address,address,address)"
      | "associateToken"
      | "associateToken(address,address)"
      | "balanceOf"
      | "balanceOf(address,address)"
      | "burnToken"
      | "burnToken(address,uint256,bytes[])"
      | "clearTransferResults"
      | "clearTransferResults()"
      | "createToken"
      | "createToken((string,string,address,string,bool,uint32,bool,address[],address[],address[],address[],address[],uint8,address,uint32),uint256,uint8[],address[])"
      | "disassociateToken"
      | "disassociateToken(address,address)"
      | "getLastTransfer"
      | "getLastTransfer(address)"
      | "getMockHtsPrecompile"
      | "getMockHtsPrecompile()"
      | "getRecordedCalls"
      | "getRecordedCalls()"
      | "getSkipAllowanceChecks"
      | "getSkipAllowanceChecks()"
      | "getSupplyKeyHolder"
      | "getSupplyKeyHolder(address)"
      | "isSupplyKey"
      | "isSupplyKey(address,address)"
      | "isTokenAssociated"
      | "isTokenAssociated(address,address)"
      | "mintToken"
      | "mintToken(address,uint256,bytes[])"
      | "mockCreateTokenResponse"
      | "mockCreateTokenResponse(int64,address)"
      | "mockIsSupplyKey"
      | "mockIsSupplyKey(address,address,bool)"
      | "revokeTokenAssociation"
      | "revokeTokenAssociation(address,address)"
      | "setAllowance"
      | "setAllowance(address,address,address,uint256)"
      | "setBalance"
      | "setBalance(address,address,uint256)"
      | "setMintFailure"
      | "setMintFailure(address,bool)"
      | "setMintingEnabled"
      | "setMintingEnabled(address,bool)"
      | "setMockHtsPrecompile"
      | "setMockHtsPrecompile(address)"
      | "setSkipAllowanceChecks"
      | "setSkipAllowanceChecks(bool)"
      | "setSupplyKeyHolder"
      | "setSupplyKeyHolder(address,address)"
      | "setTokenAssociated"
      | "setTokenAssociated(address,address,bool)"
      | "setTransferFailure"
      | "setTransferFailure(address,bool)"
      | "setTransferResult"
      | "setTransferResult(address,int64)"
      | "setupTokens"
      | "setupTokens(address,address,address,address)"
      | "transferToken"
      | "transferToken(address,address,address,uint256)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TokenAssociated"
      | "TokenAssociated(address,address)"
      | "TokenBurned"
      | "TokenBurned(address,uint256)"
      | "TokenCreated"
      | "TokenCreated(address,string,string,address)"
      | "TokenMinted"
      | "TokenMinted(address,uint256)"
      | "TokenTransferred"
      | "TokenTransferred(address,address,address,uint256)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance(address,address,address)",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "associateToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "associateToken(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnToken",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burnToken(address,uint256,bytes[])",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "clearTransferResults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clearTransferResults()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [
      IHederaTokenService.HederaTokenStruct,
      BigNumberish,
      BigNumberish[],
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken((string,string,address,string,bool,uint32,bool,address[],address[],address[],address[],address[],uint8,address,uint32),uint256,uint8[],address[])",
    values: [
      IHederaTokenService.HederaTokenStruct,
      BigNumberish,
      BigNumberish[],
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disassociateToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disassociateToken(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastTransfer(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMockHtsPrecompile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMockHtsPrecompile()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordedCalls",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordedCalls()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSkipAllowanceChecks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSkipAllowanceChecks()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyKeyHolder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyKeyHolder(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupplyKey",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupplyKey(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenAssociated",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenAssociated(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToken",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToken(address,uint256,bytes[])",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mockCreateTokenResponse",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mockCreateTokenResponse(int64,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mockIsSupplyKey",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "mockIsSupplyKey(address,address,bool)",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTokenAssociation",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTokenAssociation(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowance",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowance(address,address,address,uint256)",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBalance",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBalance(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintFailure",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintFailure(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingEnabled",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingEnabled(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMockHtsPrecompile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMockHtsPrecompile(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSkipAllowanceChecks",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSkipAllowanceChecks(bool)",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyKeyHolder",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyKeyHolder(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAssociated",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAssociated(address,address,bool)",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferFailure",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferFailure(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferResult",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferResult(address,int64)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setupTokens",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setupTokens(address,address,address,address)",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToken",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToken(address,address,address,uint256)",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowance(address,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "associateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "associateToken(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOf(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnToken(address,uint256,bytes[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearTransferResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearTransferResults()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken((string,string,address,string,bool,uint32,bool,address[],address[],address[],address[],address[],uint8,address,uint32),uint256,uint8[],address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disassociateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disassociateToken(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastTransfer(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMockHtsPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMockHtsPrecompile()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordedCalls",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordedCalls()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkipAllowanceChecks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkipAllowanceChecks()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyKeyHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyKeyHolder(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupplyKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupplyKey(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenAssociated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenAssociated(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintToken(address,uint256,bytes[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockCreateTokenResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockCreateTokenResponse(int64,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockIsSupplyKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockIsSupplyKey(address,address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTokenAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTokenAssociation(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowance(address,address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBalance(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintFailure(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingEnabled(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMockHtsPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMockHtsPrecompile(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSkipAllowanceChecks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSkipAllowanceChecks(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyKeyHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyKeyHolder(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAssociated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAssociated(address,address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferFailure(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferResult(address,int64)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupTokens(address,address,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToken(address,address,address,uint256)",
    data: BytesLike
  ): Result;
}

export namespace TokenAssociatedEvent {
  export type InputTuple = [account: AddressLike, token: AddressLike];
  export type OutputTuple = [account: string, token: string];
  export interface OutputObject {
    account: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBurnedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    token: AddressLike,
    name: string,
    symbol: string,
    treasury: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    name: string,
    symbol: string,
    treasury: string
  ];
  export interface OutputObject {
    token: string;
    name: string;
    symbol: string;
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenMintedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenTransferredEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockHederaTokenService extends BaseContract {
  contractName: "MockHederaTokenService";

  connect(runner?: ContractRunner | null): MockHederaTokenService;
  waitForDeployment(): Promise<this>;

  interface: MockHederaTokenServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [token: AddressLike, owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  "allowance(address,address,address)": TypedContractMethod<
    [token: AddressLike, owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  associateToken: TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;

  "associateToken(address,address)": TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  "balanceOf(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  burnToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;

  "burnToken(address,uint256,bytes[])": TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;

  clearTransferResults: TypedContractMethod<[], [void], "nonpayable">;

  "clearTransferResults()": TypedContractMethod<[], [void], "nonpayable">;

  createToken: TypedContractMethod<
    [
      token: IHederaTokenService.HederaTokenStruct,
      initialTotalSupply: BigNumberish,
      keys: BigNumberish[],
      keyAddresses: AddressLike[]
    ],
    [[bigint, string] & { responseCode: bigint; tokenAddress: string }],
    "payable"
  >;

  "createToken((string,string,address,string,bool,uint32,bool,address[],address[],address[],address[],address[],uint8,address,uint32),uint256,uint8[],address[])": TypedContractMethod<
    [
      token: IHederaTokenService.HederaTokenStruct,
      initialTotalSupply: BigNumberish,
      keys: BigNumberish[],
      keyAddresses: AddressLike[]
    ],
    [[bigint, string] & { responseCode: bigint; tokenAddress: string }],
    "payable"
  >;

  disassociateToken: TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;

  "disassociateToken(address,address)": TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getLastTransfer: TypedContractMethod<
    [token: AddressLike],
    [MockHederaTokenService.TransferStructOutput],
    "view"
  >;

  "getLastTransfer(address)": TypedContractMethod<
    [token: AddressLike],
    [MockHederaTokenService.TransferStructOutput],
    "view"
  >;

  getMockHtsPrecompile: TypedContractMethod<[], [string], "view">;

  "getMockHtsPrecompile()": TypedContractMethod<[], [string], "view">;

  getRecordedCalls: TypedContractMethod<[], [string[]], "view">;

  "getRecordedCalls()": TypedContractMethod<[], [string[]], "view">;

  getSkipAllowanceChecks: TypedContractMethod<[], [boolean], "view">;

  "getSkipAllowanceChecks()": TypedContractMethod<[], [boolean], "view">;

  getSupplyKeyHolder: TypedContractMethod<
    [token: AddressLike],
    [string],
    "view"
  >;

  "getSupplyKeyHolder(address)": TypedContractMethod<
    [token: AddressLike],
    [string],
    "view"
  >;

  isSupplyKey: TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike],
    [boolean],
    "view"
  >;

  "isSupplyKey(address,address)": TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike],
    [boolean],
    "view"
  >;

  isTokenAssociated: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [boolean],
    "view"
  >;

  "isTokenAssociated(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [boolean],
    "view"
  >;

  mintToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;

  "mintToken(address,uint256,bytes[])": TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;

  mockCreateTokenResponse: TypedContractMethod<
    [responseCode: BigNumberish, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  "mockCreateTokenResponse(int64,address)": TypedContractMethod<
    [responseCode: BigNumberish, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  mockIsSupplyKey: TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike, result: boolean],
    [void],
    "nonpayable"
  >;

  "mockIsSupplyKey(address,address,bool)": TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike, result: boolean],
    [void],
    "nonpayable"
  >;

  revokeTokenAssociation: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  "revokeTokenAssociation(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAllowance: TypedContractMethod<
    [
      token: AddressLike,
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "setAllowance(address,address,address,uint256)": TypedContractMethod<
    [
      token: AddressLike,
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setBalance: TypedContractMethod<
    [token: AddressLike, account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "setBalance(address,address,uint256)": TypedContractMethod<
    [token: AddressLike, account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMintFailure: TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;

  "setMintFailure(address,bool)": TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;

  setMintingEnabled: TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  "setMintingEnabled(address,bool)": TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setMockHtsPrecompile: TypedContractMethod<
    [_mockHtsPrecompile: AddressLike],
    [void],
    "nonpayable"
  >;

  "setMockHtsPrecompile(address)": TypedContractMethod<
    [_mockHtsPrecompile: AddressLike],
    [void],
    "nonpayable"
  >;

  setSkipAllowanceChecks: TypedContractMethod<
    [skip: boolean],
    [void],
    "nonpayable"
  >;

  "setSkipAllowanceChecks(bool)": TypedContractMethod<
    [skip: boolean],
    [void],
    "nonpayable"
  >;

  setSupplyKeyHolder: TypedContractMethod<
    [token: AddressLike, supplyKeyHolder: AddressLike],
    [void],
    "nonpayable"
  >;

  "setSupplyKeyHolder(address,address)": TypedContractMethod<
    [token: AddressLike, supplyKeyHolder: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenAssociated: TypedContractMethod<
    [account: AddressLike, token: AddressLike, associated: boolean],
    [void],
    "nonpayable"
  >;

  "setTokenAssociated(address,address,bool)": TypedContractMethod<
    [account: AddressLike, token: AddressLike, associated: boolean],
    [void],
    "nonpayable"
  >;

  setTransferFailure: TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;

  "setTransferFailure(address,bool)": TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;

  setTransferResult: TypedContractMethod<
    [token: AddressLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;

  "setTransferResult(address,int64)": TypedContractMethod<
    [token: AddressLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;

  setupTokens: TypedContractMethod<
    [
      lynxToken: AddressLike,
      sauceToken: AddressLike,
      clxyToken: AddressLike,
      lynxMinter: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  "setupTokens(address,address,address,address)": TypedContractMethod<
    [
      lynxToken: AddressLike,
      sauceToken: AddressLike,
      clxyToken: AddressLike,
      lynxMinter: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  transferToken: TypedContractMethod<
    [
      token: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  "transferToken(address,address,address,uint256)": TypedContractMethod<
    [
      token: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [token: AddressLike, owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowance(address,address,address)"
  ): TypedContractMethod<
    [token: AddressLike, owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "associateToken"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "associateToken(address,address)"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "burnToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnToken(address,uint256,bytes[])"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "clearTransferResults"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clearTransferResults()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [
      token: IHederaTokenService.HederaTokenStruct,
      initialTotalSupply: BigNumberish,
      keys: BigNumberish[],
      keyAddresses: AddressLike[]
    ],
    [[bigint, string] & { responseCode: bigint; tokenAddress: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createToken((string,string,address,string,bool,uint32,bool,address[],address[],address[],address[],address[],uint8,address,uint32),uint256,uint8[],address[])"
  ): TypedContractMethod<
    [
      token: IHederaTokenService.HederaTokenStruct,
      initialTotalSupply: BigNumberish,
      keys: BigNumberish[],
      keyAddresses: AddressLike[]
    ],
    [[bigint, string] & { responseCode: bigint; tokenAddress: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disassociateToken"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disassociateToken(address,address)"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLastTransfer"
  ): TypedContractMethod<
    [token: AddressLike],
    [MockHederaTokenService.TransferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastTransfer(address)"
  ): TypedContractMethod<
    [token: AddressLike],
    [MockHederaTokenService.TransferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMockHtsPrecompile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMockHtsPrecompile()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRecordedCalls"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordedCalls()"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSkipAllowanceChecks"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSkipAllowanceChecks()"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSupplyKeyHolder"
  ): TypedContractMethod<[token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSupplyKeyHolder(address)"
  ): TypedContractMethod<[token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isSupplyKey"
  ): TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupplyKey(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenAssociated"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenAssociated(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintToken(address,uint256,bytes[])"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mockCreateTokenResponse"
  ): TypedContractMethod<
    [responseCode: BigNumberish, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mockCreateTokenResponse(int64,address)"
  ): TypedContractMethod<
    [responseCode: BigNumberish, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mockIsSupplyKey"
  ): TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike, result: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mockIsSupplyKey(address,address,bool)"
  ): TypedContractMethod<
    [token: AddressLike, supplyAddress: AddressLike, result: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeTokenAssociation"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeTokenAssociation(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowance"
  ): TypedContractMethod<
    [
      token: AddressLike,
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowance(address,address,address,uint256)"
  ): TypedContractMethod<
    [
      token: AddressLike,
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBalance"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBalance(address,address,uint256)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMintFailure"
  ): TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMintFailure(address,bool)"
  ): TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMintingEnabled"
  ): TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMintingEnabled(address,bool)"
  ): TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMockHtsPrecompile"
  ): TypedContractMethod<
    [_mockHtsPrecompile: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMockHtsPrecompile(address)"
  ): TypedContractMethod<
    [_mockHtsPrecompile: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSkipAllowanceChecks"
  ): TypedContractMethod<[skip: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSkipAllowanceChecks(bool)"
  ): TypedContractMethod<[skip: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSupplyKeyHolder"
  ): TypedContractMethod<
    [token: AddressLike, supplyKeyHolder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSupplyKeyHolder(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, supplyKeyHolder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenAssociated"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike, associated: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenAssociated(address,address,bool)"
  ): TypedContractMethod<
    [account: AddressLike, token: AddressLike, associated: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTransferFailure"
  ): TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTransferFailure(address,bool)"
  ): TypedContractMethod<
    [token: AddressLike, shouldFail: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTransferResult"
  ): TypedContractMethod<
    [token: AddressLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTransferResult(address,int64)"
  ): TypedContractMethod<
    [token: AddressLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupTokens"
  ): TypedContractMethod<
    [
      lynxToken: AddressLike,
      sauceToken: AddressLike,
      clxyToken: AddressLike,
      lynxMinter: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupTokens(address,address,address,address)"
  ): TypedContractMethod<
    [
      lynxToken: AddressLike,
      sauceToken: AddressLike,
      clxyToken: AddressLike,
      lynxMinter: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferToken(address,address,address,uint256)"
  ): TypedContractMethod<
    [
      token: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "TokenAssociated"
  ): TypedContractEvent<
    TokenAssociatedEvent.InputTuple,
    TokenAssociatedEvent.OutputTuple,
    TokenAssociatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAssociated(address,address)"
  ): TypedContractEvent<
    TokenAssociated_address_address_Event.InputTuple,
    TokenAssociated_address_address_Event.OutputTuple,
    TokenAssociated_address_address_Event.OutputObject
  >;
  getEvent(
    key: "TokenBurned"
  ): TypedContractEvent<
    TokenBurnedEvent.InputTuple,
    TokenBurnedEvent.OutputTuple,
    TokenBurnedEvent.OutputObject
  >;
  getEvent(
    key: "TokenBurned(address,uint256)"
  ): TypedContractEvent<
    TokenBurned_address_uint256_Event.InputTuple,
    TokenBurned_address_uint256_Event.OutputTuple,
    TokenBurned_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated(address,string,string,address)"
  ): TypedContractEvent<
    TokenCreated_address_string_string_address_Event.InputTuple,
    TokenCreated_address_string_string_address_Event.OutputTuple,
    TokenCreated_address_string_string_address_Event.OutputObject
  >;
  getEvent(
    key: "TokenMinted"
  ): TypedContractEvent<
    TokenMintedEvent.InputTuple,
    TokenMintedEvent.OutputTuple,
    TokenMintedEvent.OutputObject
  >;
  getEvent(
    key: "TokenMinted(address,uint256)"
  ): TypedContractEvent<
    TokenMinted_address_uint256_Event.InputTuple,
    TokenMinted_address_uint256_Event.OutputTuple,
    TokenMinted_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "TokenTransferred"
  ): TypedContractEvent<
    TokenTransferredEvent.InputTuple,
    TokenTransferredEvent.OutputTuple,
    TokenTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenTransferred(address,address,address,uint256)"
  ): TypedContractEvent<
    TokenTransferred_address_address_address_uint256_Event.InputTuple,
    TokenTransferred_address_address_address_uint256_Event.OutputTuple,
    TokenTransferred_address_address_address_uint256_Event.OutputObject
  >;

  filters: {
    "TokenAssociated(address,address)": TypedContractEvent<
      TokenAssociatedEvent.InputTuple,
      TokenAssociatedEvent.OutputTuple,
      TokenAssociatedEvent.OutputObject
    >;
    TokenAssociated: TypedContractEvent<
      TokenAssociatedEvent.InputTuple,
      TokenAssociatedEvent.OutputTuple,
      TokenAssociatedEvent.OutputObject
    >;

    "TokenBurned(address,uint256)": TypedContractEvent<
      TokenBurnedEvent.InputTuple,
      TokenBurnedEvent.OutputTuple,
      TokenBurnedEvent.OutputObject
    >;
    TokenBurned: TypedContractEvent<
      TokenBurnedEvent.InputTuple,
      TokenBurnedEvent.OutputTuple,
      TokenBurnedEvent.OutputObject
    >;

    "TokenCreated(address,string,string,address)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;

    "TokenMinted(address,uint256)": TypedContractEvent<
      TokenMintedEvent.InputTuple,
      TokenMintedEvent.OutputTuple,
      TokenMintedEvent.OutputObject
    >;
    TokenMinted: TypedContractEvent<
      TokenMintedEvent.InputTuple,
      TokenMintedEvent.OutputTuple,
      TokenMintedEvent.OutputObject
    >;

    "TokenTransferred(address,address,address,uint256)": TypedContractEvent<
      TokenTransferredEvent.InputTuple,
      TokenTransferredEvent.OutputTuple,
      TokenTransferredEvent.OutputObject
    >;
    TokenTransferred: TypedContractEvent<
      TokenTransferredEvent.InputTuple,
      TokenTransferredEvent.OutputTuple,
      TokenTransferredEvent.OutputObject
    >;
  };
}
