/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IIndexVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToken"
      | "addToken(address,uint256)"
      | "calculateRequiredDeposits"
      | "calculateRequiredDeposits(uint256)"
      | "depositToken"
      | "depositToken(address,uint256)"
      | "getComposition"
      | "getComposition()"
      | "processMint"
      | "processMint(address,uint256)"
      | "removeToken"
      | "removeToken(address)"
      | "setController"
      | "setController(address)"
      | "setIndexToken"
      | "setIndexToken(address)"
      | "updateTokenWeight"
      | "updateTokenWeight(address,uint256)"
      | "validateMint"
      | "validateMint(address,uint256)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addToken(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredDeposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredDeposits(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getComposition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getComposition()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processMint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processMint(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeToken(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setController(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIndexToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIndexToken(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenWeight",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenWeight(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateMint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateMint(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addToken(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredDeposits(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComposition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComposition()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processMint(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeToken(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIndexToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIndexToken(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenWeight(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateMint(address,uint256)",
    data: BytesLike
  ): Result;
}

export interface IIndexVault extends BaseContract {
  contractName: "IIndexVault";

  connect(runner?: ContractRunner | null): IIndexVault;
  waitForDeployment(): Promise<this>;

  interface: IIndexVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToken: TypedContractMethod<
    [_token: AddressLike, _weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  "addToken(address,uint256)": TypedContractMethod<
    [_token: AddressLike, _weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  calculateRequiredDeposits: TypedContractMethod<
    [_mintAmount: BigNumberish],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;

  "calculateRequiredDeposits(uint256)": TypedContractMethod<
    [_mintAmount: BigNumberish],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;

  depositToken: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "depositToken(address,uint256)": TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getComposition: TypedContractMethod<
    [],
    [[string[], bigint[]] & { tokens: string[]; weights: bigint[] }],
    "view"
  >;

  "getComposition()": TypedContractMethod<
    [],
    [[string[], bigint[]] & { tokens: string[]; weights: bigint[] }],
    "view"
  >;

  processMint: TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "processMint(address,uint256)": TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  "removeToken(address)": TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  setController: TypedContractMethod<
    [_controller: AddressLike],
    [void],
    "nonpayable"
  >;

  "setController(address)": TypedContractMethod<
    [_controller: AddressLike],
    [void],
    "nonpayable"
  >;

  setIndexToken: TypedContractMethod<
    [_indexToken: AddressLike],
    [void],
    "nonpayable"
  >;

  "setIndexToken(address)": TypedContractMethod<
    [_indexToken: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTokenWeight: TypedContractMethod<
    [_token: AddressLike, _newWeight: BigNumberish],
    [void],
    "nonpayable"
  >;

  "updateTokenWeight(address,uint256)": TypedContractMethod<
    [_token: AddressLike, _newWeight: BigNumberish],
    [void],
    "nonpayable"
  >;

  validateMint: TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [boolean],
    "view"
  >;

  "validateMint(address,uint256)": TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToken"
  ): TypedContractMethod<
    [_token: AddressLike, _weight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addToken(address,uint256)"
  ): TypedContractMethod<
    [_token: AddressLike, _weight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateRequiredDeposits"
  ): TypedContractMethod<
    [_mintAmount: BigNumberish],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRequiredDeposits(uint256)"
  ): TypedContractMethod<
    [_mintAmount: BigNumberish],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositToken(address,uint256)"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getComposition"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { tokens: string[]; weights: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComposition()"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { tokens: string[]; weights: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "processMint"
  ): TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processMint(address,uint256)"
  ): TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeToken(address)"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setController"
  ): TypedContractMethod<[_controller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setController(address)"
  ): TypedContractMethod<[_controller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIndexToken"
  ): TypedContractMethod<[_indexToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIndexToken(address)"
  ): TypedContractMethod<[_indexToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTokenWeight"
  ): TypedContractMethod<
    [_token: AddressLike, _newWeight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTokenWeight(address,uint256)"
  ): TypedContractMethod<
    [_token: AddressLike, _newWeight: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateMint"
  ): TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateMint(address,uint256)"
  ): TypedContractMethod<
    [_user: AddressLike, _mintAmount: BigNumberish],
    [boolean],
    "view"
  >;

  filters: {};
}
