/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DepositMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DepositMinter__factory>;
    getContractFactory(
      name: "HederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HederaTokenService__factory>;
    getContractFactory(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService__factory>;
    getContractFactory(
      name: "IndexTokenController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexTokenController__factory>;
    getContractFactory(
      name: "IndexVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IndexVault__factory>;
    getContractFactory(
      name: "MockHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHederaTokenService__factory>;
    getContractFactory(
      name: "SimpleTokenMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleTokenMinter__factory>;

    getContractAt(
      name: "DepositMinter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DepositMinter>;
    getContractAt(
      name: "HederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HederaTokenService>;
    getContractAt(
      name: "IHederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHederaTokenService>;
    getContractAt(
      name: "IndexTokenController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexTokenController>;
    getContractAt(
      name: "IndexVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IndexVault>;
    getContractAt(
      name: "MockHederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHederaTokenService>;
    getContractAt(
      name: "SimpleTokenMinter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleTokenMinter>;

    deployContract(
      name: "DepositMinter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DepositMinter>;
    deployContract(
      name: "HederaTokenService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HederaTokenService>;
    deployContract(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "IndexTokenController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexTokenController>;
    deployContract(
      name: "IndexVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexVault>;
    deployContract(
      name: "MockHederaTokenService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHederaTokenService>;
    deployContract(
      name: "SimpleTokenMinter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleTokenMinter>;

    deployContract(
      name: "DepositMinter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DepositMinter>;
    deployContract(
      name: "HederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HederaTokenService>;
    deployContract(
      name: "IHederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "IndexTokenController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexTokenController>;
    deployContract(
      name: "IndexVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IndexVault>;
    deployContract(
      name: "MockHederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHederaTokenService>;
    deployContract(
      name: "SimpleTokenMinter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleTokenMinter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
