/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IndexTokenControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN"
      | "ADMIN()"
      | "AUTO_RENEW_PERIOD"
      | "AUTO_RENEW_PERIOD()"
      | "HTS_PRECOMPILE"
      | "HTS_PRECOMPILE()"
      | "INDEX_TOKEN"
      | "INDEX_TOKEN()"
      | "IS_SUPPLY_TYPE_INFINITE"
      | "IS_SUPPLY_TYPE_INFINITE()"
      | "TOKEN_DECIMALS"
      | "TOKEN_DECIMALS()"
      | "TOKEN_MAX_SUPPLY"
      | "TOKEN_MAX_SUPPLY()"
      | "calculateRequiredDeposits"
      | "calculateRequiredDeposits(uint256)"
      | "checkSupplyKey"
      | "checkSupplyKey()"
      | "createIndexToken"
      | "createIndexToken(string,string,string)"
      | "getTokenAddress"
      | "getTokenAddress()"
      | "hasSupplyKey"
      | "hasSupplyKey()"
      | "mintTo"
      | "mintTo(address,uint256)"
      | "setIndexTokenId"
      | "setIndexTokenId(address)"
      | "setSupplyKeyStatus"
      | "setSupplyKeyStatus(bool)"
      | "setTokenService"
      | "setTokenService(address)"
      | "updateSupplyKeyStatus"
      | "updateSupplyKeyStatus()"
      | "vault"
      | "vault()"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IndexTokenCreated"
      | "IndexTokenCreated(address,int64)"
      | "IndexTokenMinted"
      | "IndexTokenMinted(address,uint256)"
      | "IndexTokenSet"
      | "IndexTokenSet(address)"
      | "SupplyKeyVerified"
      | "SupplyKeyVerified(bool)"
      | "TokenAssociationAttempt"
      | "TokenAssociationAttempt(address,address,int64)"
      | "TokenCreationAttempt"
      | "TokenCreationAttempt(string,string,address,address[],address[],address[])"
      | "TokenCreationResponse"
      | "TokenCreationResponse(int64,address,string)"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ADMIN", values?: undefined): string;
  encodeFunctionData(functionFragment: "ADMIN()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "AUTO_RENEW_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUTO_RENEW_PERIOD()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HTS_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HTS_PRECOMPILE()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INDEX_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INDEX_TOKEN()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IS_SUPPLY_TYPE_INFINITE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IS_SUPPLY_TYPE_INFINITE()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_DECIMALS()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_MAX_SUPPLY()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredDeposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredDeposits(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSupplyKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkSupplyKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createIndexToken",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createIndexToken(string,string,string)",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddress()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSupplyKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSupplyKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintTo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintTo(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIndexTokenId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIndexTokenId(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyKeyStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyKeyStatus(bool)",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenService",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenService(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSupplyKeyStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSupplyKeyStatus()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(functionFragment: "vault()", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ADMIN()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "AUTO_RENEW_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUTO_RENEW_PERIOD()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HTS_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HTS_PRECOMPILE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INDEX_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INDEX_TOKEN()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IS_SUPPLY_TYPE_INFINITE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IS_SUPPLY_TYPE_INFINITE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_DECIMALS()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_MAX_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_MAX_SUPPLY()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredDeposits(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSupplyKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSupplyKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIndexToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIndexToken(string,string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddress()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSupplyKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSupplyKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintTo(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIndexTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIndexTokenId(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyKeyStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyKeyStatus(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenService(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSupplyKeyStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSupplyKeyStatus()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault()", data: BytesLike): Result;
}

export namespace IndexTokenCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    responseCode: BigNumberish
  ];
  export type OutputTuple = [tokenAddress: string, responseCode: bigint];
  export interface OutputObject {
    tokenAddress: string;
    responseCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndexTokenMintedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndexTokenSetEvent {
  export type InputTuple = [tokenAddress: AddressLike];
  export type OutputTuple = [tokenAddress: string];
  export interface OutputObject {
    tokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyKeyVerifiedEvent {
  export type InputTuple = [hasKey: boolean];
  export type OutputTuple = [hasKey: boolean];
  export interface OutputObject {
    hasKey: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAssociationAttemptEvent {
  export type InputTuple = [
    account: AddressLike,
    token: AddressLike,
    responseCode: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    token: string,
    responseCode: bigint
  ];
  export interface OutputObject {
    account: string;
    token: string;
    responseCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreationAttemptEvent {
  export type InputTuple = [
    name: string,
    symbol: string,
    treasury: AddressLike,
    supplyKey: AddressLike[],
    adminKey: AddressLike[],
    autoRenewKey: AddressLike[]
  ];
  export type OutputTuple = [
    name: string,
    symbol: string,
    treasury: string,
    supplyKey: string[],
    adminKey: string[],
    autoRenewKey: string[]
  ];
  export interface OutputObject {
    name: string;
    symbol: string;
    treasury: string;
    supplyKey: string[];
    adminKey: string[];
    autoRenewKey: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreationResponseEvent {
  export type InputTuple = [
    responseCode: BigNumberish,
    tokenAddress: AddressLike,
    errorMessage: string
  ];
  export type OutputTuple = [
    responseCode: bigint,
    tokenAddress: string,
    errorMessage: string
  ];
  export interface OutputObject {
    responseCode: bigint;
    tokenAddress: string;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IndexTokenController extends BaseContract {
  contractName: "IndexTokenController";

  connect(runner?: ContractRunner | null): IndexTokenController;
  waitForDeployment(): Promise<this>;

  interface: IndexTokenControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN: TypedContractMethod<[], [string], "view">;

  "ADMIN()": TypedContractMethod<[], [string], "view">;

  AUTO_RENEW_PERIOD: TypedContractMethod<[], [bigint], "view">;

  "AUTO_RENEW_PERIOD()": TypedContractMethod<[], [bigint], "view">;

  HTS_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  "HTS_PRECOMPILE()": TypedContractMethod<[], [string], "view">;

  INDEX_TOKEN: TypedContractMethod<[], [string], "view">;

  "INDEX_TOKEN()": TypedContractMethod<[], [string], "view">;

  IS_SUPPLY_TYPE_INFINITE: TypedContractMethod<[], [boolean], "view">;

  "IS_SUPPLY_TYPE_INFINITE()": TypedContractMethod<[], [boolean], "view">;

  TOKEN_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  "TOKEN_DECIMALS()": TypedContractMethod<[], [bigint], "view">;

  TOKEN_MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  "TOKEN_MAX_SUPPLY()": TypedContractMethod<[], [bigint], "view">;

  calculateRequiredDeposits: TypedContractMethod<
    [amount: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  "calculateRequiredDeposits(uint256)": TypedContractMethod<
    [amount: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  checkSupplyKey: TypedContractMethod<[], [void], "nonpayable">;

  "checkSupplyKey()": TypedContractMethod<[], [void], "nonpayable">;

  createIndexToken: TypedContractMethod<
    [name: string, symbol: string, memo: string],
    [void],
    "payable"
  >;

  "createIndexToken(string,string,string)": TypedContractMethod<
    [name: string, symbol: string, memo: string],
    [void],
    "payable"
  >;

  getTokenAddress: TypedContractMethod<[], [string], "view">;

  "getTokenAddress()": TypedContractMethod<[], [string], "view">;

  hasSupplyKey: TypedContractMethod<[], [boolean], "view">;

  "hasSupplyKey()": TypedContractMethod<[], [boolean], "view">;

  mintTo: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "mintTo(address,uint256)": TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setIndexTokenId: TypedContractMethod<
    [newIndexTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  "setIndexTokenId(address)": TypedContractMethod<
    [newIndexTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setSupplyKeyStatus: TypedContractMethod<
    [status: boolean],
    [void],
    "nonpayable"
  >;

  "setSupplyKeyStatus(bool)": TypedContractMethod<
    [status: boolean],
    [void],
    "nonpayable"
  >;

  setTokenService: TypedContractMethod<
    [mockHts: AddressLike],
    [void],
    "nonpayable"
  >;

  "setTokenService(address)": TypedContractMethod<
    [mockHts: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSupplyKeyStatus: TypedContractMethod<[], [void], "nonpayable">;

  "updateSupplyKeyStatus()": TypedContractMethod<[], [void], "nonpayable">;

  vault: TypedContractMethod<[], [string], "view">;

  "vault()": TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ADMIN()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUTO_RENEW_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "AUTO_RENEW_PERIOD()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HTS_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "HTS_PRECOMPILE()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INDEX_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INDEX_TOKEN()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IS_SUPPLY_TYPE_INFINITE"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "IS_SUPPLY_TYPE_INFINITE()"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "TOKEN_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_DECIMALS()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_MAX_SUPPLY()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateRequiredDeposits"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRequiredDeposits(uint256)"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkSupplyKey"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkSupplyKey()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createIndexToken"
  ): TypedContractMethod<
    [name: string, symbol: string, memo: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createIndexToken(string,string,string)"
  ): TypedContractMethod<
    [name: string, symbol: string, memo: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenAddress()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasSupplyKey"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasSupplyKey()"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintTo"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintTo(address,uint256)"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIndexTokenId"
  ): TypedContractMethod<
    [newIndexTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIndexTokenId(address)"
  ): TypedContractMethod<
    [newIndexTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSupplyKeyStatus"
  ): TypedContractMethod<[status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSupplyKeyStatus(bool)"
  ): TypedContractMethod<[status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenService"
  ): TypedContractMethod<[mockHts: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenService(address)"
  ): TypedContractMethod<[mockHts: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSupplyKeyStatus"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSupplyKeyStatus()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vault()"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "IndexTokenCreated"
  ): TypedContractEvent<
    IndexTokenCreatedEvent.InputTuple,
    IndexTokenCreatedEvent.OutputTuple,
    IndexTokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IndexTokenCreated(address,int64)"
  ): TypedContractEvent<
    IndexTokenCreated_address_int64_Event.InputTuple,
    IndexTokenCreated_address_int64_Event.OutputTuple,
    IndexTokenCreated_address_int64_Event.OutputObject
  >;
  getEvent(
    key: "IndexTokenMinted"
  ): TypedContractEvent<
    IndexTokenMintedEvent.InputTuple,
    IndexTokenMintedEvent.OutputTuple,
    IndexTokenMintedEvent.OutputObject
  >;
  getEvent(
    key: "IndexTokenMinted(address,uint256)"
  ): TypedContractEvent<
    IndexTokenMinted_address_uint256_Event.InputTuple,
    IndexTokenMinted_address_uint256_Event.OutputTuple,
    IndexTokenMinted_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "IndexTokenSet"
  ): TypedContractEvent<
    IndexTokenSetEvent.InputTuple,
    IndexTokenSetEvent.OutputTuple,
    IndexTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "IndexTokenSet(address)"
  ): TypedContractEvent<
    IndexTokenSet_address_Event.InputTuple,
    IndexTokenSet_address_Event.OutputTuple,
    IndexTokenSet_address_Event.OutputObject
  >;
  getEvent(
    key: "SupplyKeyVerified"
  ): TypedContractEvent<
    SupplyKeyVerifiedEvent.InputTuple,
    SupplyKeyVerifiedEvent.OutputTuple,
    SupplyKeyVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyKeyVerified(bool)"
  ): TypedContractEvent<
    SupplyKeyVerified_bool_Event.InputTuple,
    SupplyKeyVerified_bool_Event.OutputTuple,
    SupplyKeyVerified_bool_Event.OutputObject
  >;
  getEvent(
    key: "TokenAssociationAttempt"
  ): TypedContractEvent<
    TokenAssociationAttemptEvent.InputTuple,
    TokenAssociationAttemptEvent.OutputTuple,
    TokenAssociationAttemptEvent.OutputObject
  >;
  getEvent(
    key: "TokenAssociationAttempt(address,address,int64)"
  ): TypedContractEvent<
    TokenAssociationAttempt_address_address_int64_Event.InputTuple,
    TokenAssociationAttempt_address_address_int64_Event.OutputTuple,
    TokenAssociationAttempt_address_address_int64_Event.OutputObject
  >;
  getEvent(
    key: "TokenCreationAttempt"
  ): TypedContractEvent<
    TokenCreationAttemptEvent.InputTuple,
    TokenCreationAttemptEvent.OutputTuple,
    TokenCreationAttemptEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreationAttempt(string,string,address,address[],address[],address[])"
  ): TypedContractEvent<
    TokenCreationAttempt_string_string_address_address_array_address_array_address_array_Event.InputTuple,
    TokenCreationAttempt_string_string_address_address_array_address_array_address_array_Event.OutputTuple,
    TokenCreationAttempt_string_string_address_address_array_address_array_address_array_Event.OutputObject
  >;
  getEvent(
    key: "TokenCreationResponse"
  ): TypedContractEvent<
    TokenCreationResponseEvent.InputTuple,
    TokenCreationResponseEvent.OutputTuple,
    TokenCreationResponseEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreationResponse(int64,address,string)"
  ): TypedContractEvent<
    TokenCreationResponse_int64_address_string_Event.InputTuple,
    TokenCreationResponse_int64_address_string_Event.OutputTuple,
    TokenCreationResponse_int64_address_string_Event.OutputObject
  >;

  filters: {
    "IndexTokenCreated(address,int64)": TypedContractEvent<
      IndexTokenCreatedEvent.InputTuple,
      IndexTokenCreatedEvent.OutputTuple,
      IndexTokenCreatedEvent.OutputObject
    >;
    IndexTokenCreated: TypedContractEvent<
      IndexTokenCreatedEvent.InputTuple,
      IndexTokenCreatedEvent.OutputTuple,
      IndexTokenCreatedEvent.OutputObject
    >;

    "IndexTokenMinted(address,uint256)": TypedContractEvent<
      IndexTokenMintedEvent.InputTuple,
      IndexTokenMintedEvent.OutputTuple,
      IndexTokenMintedEvent.OutputObject
    >;
    IndexTokenMinted: TypedContractEvent<
      IndexTokenMintedEvent.InputTuple,
      IndexTokenMintedEvent.OutputTuple,
      IndexTokenMintedEvent.OutputObject
    >;

    "IndexTokenSet(address)": TypedContractEvent<
      IndexTokenSetEvent.InputTuple,
      IndexTokenSetEvent.OutputTuple,
      IndexTokenSetEvent.OutputObject
    >;
    IndexTokenSet: TypedContractEvent<
      IndexTokenSetEvent.InputTuple,
      IndexTokenSetEvent.OutputTuple,
      IndexTokenSetEvent.OutputObject
    >;

    "SupplyKeyVerified(bool)": TypedContractEvent<
      SupplyKeyVerifiedEvent.InputTuple,
      SupplyKeyVerifiedEvent.OutputTuple,
      SupplyKeyVerifiedEvent.OutputObject
    >;
    SupplyKeyVerified: TypedContractEvent<
      SupplyKeyVerifiedEvent.InputTuple,
      SupplyKeyVerifiedEvent.OutputTuple,
      SupplyKeyVerifiedEvent.OutputObject
    >;

    "TokenAssociationAttempt(address,address,int64)": TypedContractEvent<
      TokenAssociationAttemptEvent.InputTuple,
      TokenAssociationAttemptEvent.OutputTuple,
      TokenAssociationAttemptEvent.OutputObject
    >;
    TokenAssociationAttempt: TypedContractEvent<
      TokenAssociationAttemptEvent.InputTuple,
      TokenAssociationAttemptEvent.OutputTuple,
      TokenAssociationAttemptEvent.OutputObject
    >;

    "TokenCreationAttempt(string,string,address,address[],address[],address[])": TypedContractEvent<
      TokenCreationAttemptEvent.InputTuple,
      TokenCreationAttemptEvent.OutputTuple,
      TokenCreationAttemptEvent.OutputObject
    >;
    TokenCreationAttempt: TypedContractEvent<
      TokenCreationAttemptEvent.InputTuple,
      TokenCreationAttemptEvent.OutputTuple,
      TokenCreationAttemptEvent.OutputObject
    >;

    "TokenCreationResponse(int64,address,string)": TypedContractEvent<
      TokenCreationResponseEvent.InputTuple,
      TokenCreationResponseEvent.OutputTuple,
      TokenCreationResponseEvent.OutputObject
    >;
    TokenCreationResponse: TypedContractEvent<
      TokenCreationResponseEvent.InputTuple,
      TokenCreationResponseEvent.OutputTuple,
      TokenCreationResponseEvent.OutputObject
    >;
  };
}
