/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DepositMinterV2 } from "./DepositMinterV2";
export type { IHederaTokenService } from "./IHederaTokenService";
